[Fix] 대댓글이 존재하는 댓글 연속 삭제 가능 오류
dormitoryFamilies/BE pull request #24
Opened 2024-02-21 17:45 UTC by somln

## 🎯 목적

- [x] 버그 수정 (Bug Fix)

### - **간략한 설명**
  - 대댓글이 존재하는 댓글 연속 삭제 가능 오류를 해결하였습니다.

---

## 🛠 주요 작성/변경 사항
  - isDeleted가 true인지 확인하는 코드를 추가했습니다.
 <img src="https://github.com/dormitoryFamilies/BE/assets/92261242/991a72cf-66ef-4801-bc3b-a4d0d40393eb" width="70%">

---

## 💡 특이 사항 및 고민사항
- 추가적으로 댓글과 대댓글 전체 코드를 정리하였습니다.

---

## 🔗 관련 이슈

- **이슈 링크** : #23

---

## 📮 리뷰어에게 전하는 메시지
- 오류 찾아주셔서 감사합니다!

2024-02-21 19:21 UTC, meena2003 requested changes
소민님, 오류 관련한 커밋만 남도록 아까 저희 같이 했던 것처럼 develop에 최신화 된 커밋들을 fix/#23-fix-comment로 리베이스 해주세요!

2024-02-21 19:28 UTC, somln commented
> fix/#23-fix-comment

코드 일괄 정리도 이 브랜치에서 진행했습니다..!!

2024-02-22 15:35 UTC, meena2003 approved these changes
커밋하기 전에, 인텔리제이의 코드 정렬 기준을 사용하시면 좋겠어요!
수정하신 파일들의 상위 디렉토리를 클릭하신 뒤, 윈도우 기준으로 contrl + alt + shift + L 버튼을 눌러보세요.

고생하셨습니다 💯

2024-02-22 15:35 UTC, meena2003 commented on src/main/java/dormitoryfamily/doomz/domain/comment/dto/response/CommentResponseDto.java
> +
적용해 주셨네요 👍

2024-02-22 15:35 UTC, meena2003 commented on src/main/java/dormitoryfamily/doomz/domain/comment/entity/Comment.java
> +        this.isDeleted = true;
👍

2024-02-22 15:35 UTC, meena2003 commented on src/main/java/dormitoryfamily/doomz/domain/comment/service/CommentService.java
> +        if (comment.isDeleted()) {
디테일의 신이네요! ㅎㅎ

2024-02-22 15:35 UTC, meena2003 commented on src/main/java/dormitoryfamily/doomz/domain/comment/service/CommentService.java
> +        if(comment.isDeleted()&&!hasReplyComment(comment.getId())){
이것도 코드 컨벤션을 지키면 더 좋을것 같아요!
if ( 이렇게 한 칸 띄우고, 또 && 연산자 사이에도 한칸씩 띄워주세요 :)

2024-02-22 15:35 UTC, meena2003 commented on src/main/java/dormitoryfamily/doomz/domain/replyComment/dto/response/ReplyCommentResponseDto.java
> +                        isArticleWriter(loginMember,replyComment.getComment().getMember())
, 한칸 띄워주세요!

2024-02-23 14:22 UTC, merged